openapi: '3.0.2'
info:
  title: Diet Tracker
  version: '1.0'
servers:
  - url: http://localhost:8080/api 
components:
  schemas:
    Food:
      type: object
      properties:
        id: 
          type: string
        name:
          type: string
        weight:
          type: number
        caloriesPer100g:
          type: number
    FoodResponse: 
      type: object
      properties:
        length:
          type: number
        data:
          type: array
          items: 
            allOf:
              - $ref: '#/components/schemas/Food'
    FoodFull:
      allOf: 
      - $ref: '#/components/schemas/Food'
      - type: object
      properties:
        nutriScore:
          type: string
    Error:
      properties:
        message:
          type: string
paths: 
  /foods:
    get:
      summary: Get all foods
      tags:
        - All foods data
      responses:
        200:
          description: Successfull response
          content:
            "application/json":
              schema:
                type: object
                $ref: '#/components/schemas/FoodResponse'
        400:
          description: Error
          content:
            "application/json":
              schema:
                type: object  
    post:
      summary: Create a new food resource
      tags: 
        - Create new food
      requestBody:
        description: Body payload
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Food'
      responses:
        200:
          description: Successfull response
          content: 
            "application/json":
              schema:
                type: object
                $ref: '#/components/schemas/Food'
        422:
          description: Missing parameter
          content:
            "application/json":
              schema:
                type: object 
                $ref: '#/components/schemas/Error'
  /foods/{id}:
    get:
      summary: Returns food by id
      tags:
        - Single food data
      parameters:
        - name: id
          in: path
          description: food id to use
          required: true
          schema:
            type: string
      responses: 
        200:
          description: Successfull response
          content: 
            "application/json":
              schema:
                $ref: '#/components/schemas/FoodFull'
        204:
          description: Item not found
          content:
            "application/json":
              schema: 
                type: object
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete one item by id
      tags:
        - Delete single item
      parameters:
        - name: id
          in: path
          description: Food id to delete
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfull response
        204:
          description: No such id
          content:
            "application/json":
              schema:
                type: object
                $ref: '#/components/schemas/Error'
